#spring.application.name=gather_club_back
server:
  port: 8080
  address: 0.0.0.0
spring:
  datasource:
    url: jdbc:postgresql://212.67.8.92:5432/gather_club_db
    username: ramil
    password: 123456
    driver-class-name: org.postgresql.Driver
jwt:
  secret: "kdNyxKDfpa/BkcEOj8i9JcvZoLaiE6H+pR/OKURQTHoYgea/8DVyuis37n2j2vo2/7GULXclcMKnP7U4+6FBB4g="
  expiration: 86400000
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.gather_club_back: DEBUG
yandex.disk.access-token: y0__xC6zKySBhj85jcg8pfClRMw_u_z2wehf89XTSKlwjybF0fjHWc-1Yvb5g
yandex.disk.api-url: https://cloud-api.yandex.net/v1/disk
yandex.disk.base-path: /GatherClub