#spring.application.name=gather_club_back
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://212.67.8.92:5432/gather_club_db
    username: ramil
    password: 123456
    driver-class-name: org.postgresql.Driver